services:
  postgres:
    image: postgres
    container_name: donow-postgres
    environment:
      POSTGRES_PASSWORD: doitnowdb
    ports:
      - "5432:5432/tcp"
    volumes:
      - /home/Dom/Documents/donow-postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  my_postgres_data:
    driver: local

