
version: '3.9'

services:
  web:
    build: .
    ports:
      - "8080:8080" # Internal for Caddy
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/donowdb?sslmode=disable"

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: donowdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  pgdata:
  caddy_data:
  caddy_config:

